java_recruit_info/java_recruit_info/urls.py
from django.conf.urls import url, include
from job51 import views as index
urlpatterns = [
    url('^$',index.job_list),
    url(r'^job/',include("job51.urls",namespace="job")),
]

java_recruit_info/job51/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page
from . import views

app_name = 'job51'
urlpatterns = [
    url(r'^$', views.job_list, name='job_list'),
    url(r'^job/list/$', views.job_list, name='job_list'),
    url(r'^job/list/ajax/$', views.job_list_ajax, name='job_list_ajax'),
    url(r'^job/detail/(?P<job_id>\d+)$', views.job_detail, name='job_detail'),
    url(r'^job/keyword/(?P<job_id>\d+)$', views.job_keyword, name='job_keyword'),
    url(r'^job/segment_count_sum/$', views.segment_count_sum, name='segment_count_sum'),
    url(r'^job/segment_count_sum/ajax/$', views.segment_count_sum_ajax, name='segment_count_sum_ajax'),
    url(r'^job/segment_count_sum/chart/$', views.segment_count_sum_chart, name='segment_count_sum_chart'),
]

java_recruit_info/job51/models.py
from django.db import models
# Create your models here.

# 职位类
class Job(models.Model):
    job_id = models.IntegerField(primary_key=True)
    job_name = models.CharField(max_length=100)
    job_company_name = models.CharField(max_length=200)
    job_area_name = models.CharField(max_length=50)
    job_salary = models.CharField(max_length=50)

# 职位详情类
class JobDetail(models.Model):
    job_detail_id = models.AutoField(primary_key=True)
    job_company_type = models.CharField(max_length=100)
    job_publish_time = models.CharField(max_length=20)
    job_address = models.CharField(max_length=100)
    job_company_scale = models.CharField(max_length=100)
    job_require_other = models.CharField(max_length=100)
    job_description = models.TextField(blank=True)
    job_position_tag = models.CharField(max_length=1000)
    job_welfare = models.CharField(max_length=1000)
    job_cleaned_description = models.TextField(blank=True)
    job = models.ForeignKey(Job)

# 分词统计类
class SegmentCount(models.Model):
    segment_count_id = models.AutoField(primary_key=True)
    job_id = models.IntegerField()
    key_word = models.CharField(max_length=100)
    count =  models.IntegerField()

java_recruit_info/job51/views.py
from django.shortcuts import render,HttpResponse
from django.db.models import Sum
from  django.http import JsonResponse
from job51.models import Job,JobDetail,SegmentCount
import json
#获取工作列表
def job_list(request):
    return render(request,template_name="job51/job_list.html")

def job_list_ajax(request):
    jobs = Job.objects.all()
    data = []
    for job in jobs:
        data.append({'job_id': job.job_id, 'job_name': job.job_name, 'job_company_name': job.job_company_name,
                     'job_area_name': job.job_area_name,'job_salary': job.job_salary})
    json_data = json.dumps(data, default= 'utf-8')
    return HttpResponse(json_data)


#获取工作列表
def job_detail(request, job_id):
    detail = JobDetail.objects.filter(job_id=job_id)
    return render(request,template_name="job51/job_detail.html",context={'detail':detail.first()})

#某个职位的关键词信息
def job_keyword(request,job_id):
    keywords  = SegmentCount.objects.filter(job_id=job_id)
    return render(request, template_name="job51/job_keyword.html", context={'keywords': keywords})

#所有的职位的关键词汇总
def segment_count_sum(request):
    jump_to = request.GET.get('jump_to')
    print(jump_to)
    if jump_to and int(jump_to) == 1:
        return render(request, template_name="job51/segment_count_chart.html")
    else:
        return render(request, template_name="job51/segment_count_ajax.html")

def segment_count_sum_ajax(request):
    segs = SegmentCount.objects.values("key_word").annotate(s_count = Sum("count")).order_by("-s_count")
    data = []
    for seg in segs:
        print(seg)
        data.append({'key_word': seg['key_word'], 'count':seg['s_count']})
    json_data = json.dumps(data, default='utf-8')
    return HttpResponse(json_data)

def segment_count_sum_chart(request):
    segs = SegmentCount.objects.values("key_word").annotate(s_count = Sum("count"))
    keys = []
    values = []
    for seg in segs:
        keys.append(seg['key_word'])
        values.append(seg['s_count'])
    return HttpResponse(json.dumps({'keys':keys,'values':values}, default= 'utf-8'))

java_recruit_info/job51/templates/job51/job_detail.html
{% extends "job51/layout.html" %}
{% block title %} 职位详情页 {% endblock %}
{% block style %}
    <style>
         .list-content li{
              line-height: 30px;
         }
        .list-content li div{
            font-size: 16px!important;
        }
    </style>
{% endblock %}
{% block MainContent %}
      <div class="breadcrumb">
        <li>职位</li>
        <li>详情页</li>
    </div>
    <div class="page-header ">
        <h1>职位详情页</h1>
    </div>

    <ul class="list-unstyled list-content">
        <li><div class="col-sm-2">公司类型：</div><div class="col-sm-10">{{ detail.job_company_type }}</div></li>
        <li><div class="col-sm-2">发布时间：</div><div class="col-sm-10">{{ detail.job_publish_time }}</div></li>
        <li><div class="col-sm-2">地址：</div><div class="col-sm-10">{{ detail.job_address }}</div></li>
        <li><div class="col-sm-2">规模：</div><div class="col-sm-10">{{ detail.job_company_scale }}</div></li>
        <li><div class="col-sm-2">招聘要求：</div><div class="col-sm-10">{{ detail.job_require_other }}</div></li>
        <li><div class="col-sm-2">职位描述：</div><div class="col-sm-10 text-info">{{ detail.job_description }}</div></li>
        <li><div class="col-sm-2">标签：</div><div class="col-sm-10">{{ detail.job_position_tag }}</div></li>
        <li><div class="col-sm-2">福利：</div><div class="col-sm-10">{{ detail.job_welfare }}</div></li>
    </ul>
 {% endblock %}

java_recruit_info/job51/templates/job51/job_keyword.html
{% extends "job51/layout.html" %}
{% block title %} 关键词 {% endblock %}
{% block style %}
    <style>
         .list-content li{
              line-height: 30px;
         }
        .list-content li div{
            font-size: 16px!important;
        }
    </style>
{% endblock %}
{% block MainContent %}
    <div class="breadcrumb">
        <li>职位</li>
        <li>关键词</li>
    </div>
    <div class="page-header ">
        <h1>关键词统计</h1>
    </div>
        <ul class="list-unstyled list-content">
        {% for key in keywords %}
              <li><div class="col-sm-2">{{ key.key_word }}：</div><div class="col-sm-10 text-info">{{ key.count }}</div></li>
        {% endfor %}
    </ul>
{% endblock %}

java_recruit_info/job51/templates/job51/job_list.html
{% extends "job51/layout.html" %}
{% block title %} 职位列表页 {% endblock %}
{% block MainContent %}
    <div class="breadcrumb">
        <li>职位</li>
        <li>列表页</li>
    </div>
    <div class="page-header ">
        <h1>职位列表页面</h1>
    </div>
    <div id="table"></div>
    <input type="hidden" id="list_url" value="{% url 'job:job_list_ajax' %}">
    <script>
        $(function () {
            var list_url = $("#list_url").val();
            $("#table").bootstrapTable({
                url:list_url,
                method:'get',
                dataType:'json',
                contentType: "application/x-www-form-urlencoded",
                striped: true, //是否显示行间隔色
                sortable:true,
                sidePagination: "client",           //分页方式：client客户端分页，server服务端分页（*）
                showColumns:true,
                search: true,//是否显示表格搜索，此搜索是客户端搜索，不会进服务端
                pagination:true,
                queryParams:function () {
                    return {};
                },
                minimumCountColumns:2,
                pageNumber:1,                       //初始化加载第一页，默认第一页
                pageSize: 20,                       //每页的记录行数（*）
                pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
                uniqueId: "job_id",                     //每一行的唯一标识，一般为主键列
                showExport: true,
                exportDataType: 'all',
                columns:[
                    {
                        field: '',
                            title: '序号',
                            formatter: function (value, row, index) {
                            return index+1;
                         }
                    },
                    {
                        field : 'job_id',
                        title : '编号',
                        width: '10%',
                        align : 'center',
                        valign : 'middle',
                        sortable : true
                    }, {
                        field : 'job_name',
                        title : '职位名称',
                        width:  '25%',
                        align : 'center',
                        valign : 'middle',
                        sortable : true
                    }, {
                        field : 'job_company_name',
                        title : '企业名称',
                        width:  '20%',
                        align : 'center',
                        valign : 'middle'
                    }, {
                        field : 'job_area_name',
                        title : '地区',
                        width:  '10%',
                        align : 'center',
                        valign : 'middle',
                        sortable : true
                    }, {
                        field : 'job_salary',
                        title : '薪水',
                        width:  '10%',
                        align : 'center',
                        valign : 'middle'
                    }, {
                        title : '操作',
                        width:  '20%',
                        align : 'center',
                        valign : 'left',
                        formatter : function (value, row, index){
                            var html = '<a href="/job/job/detail/'+ row.job_id +'"  class = "btn btn-sm btn-primary">详情页</a> &nbsp;';
                            html +=  '<a href="/job/job/keyword/'+ row.job_id +'"  class = "btn  btn-sm btn-success">关键字</a>';
                            return html;
                        }
                    }]
            })
        });
    </script>
 {% endblock %}

java_recruit_info/job51/templates/job51/layout.html
{% load staticfiles %}
<html lang="en">
<head>
    <title>{% block title %} JOB {% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-table.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap-table.js' %}"></script>
    <script src="{% static 'js/bootstrap-table-zh-CN.js' %}"></script>
    <style>
        .navbar-brand{
            font-weight: 300;
            font-size: x-large;
            font-family: fantasy;
        }
        .Main{
            margin-top: 50px;
            min-height: 300px;
        }
        .footer{
            margin-top: 20px;
            min-width: 100%;
            text-align: center;
        }
        .fixed-table-body{
            height: inherit !important;
        }
    </style>
    {% block style %} {% endblock %}
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top header-logo">
        <div class="container">
            <div class="navbar-header">
                 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
                    <li><a class="icon-bar" href="{% url 'job:job_list' %}">职位列表</a></li>
                    <li><a class="icon-bar" href="#">关键词统计</a></li>
                </button>
                <a class="navbar-brand">job.com</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a class="btn-lg"  href="{% url 'job:job_list' %}">职位列表</a></li>
                    <li><a class="btn-lg" href="{% url 'job:segment_count_sum'%}">关键词统计</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">登陆</a></li>
                    <li><a href="#">退出</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container Main">
       {% block MainContent %} Main Content {% endblock %}
    </div>
    <div class="container footer">
       <div class="copyright">
             Copyright © 2017-2017    <strong><a href="#" target="_blank">职位统计</a></strong>&nbsp;
             All Rights Reserved. 备案号：520
       </div>
    </div>
</body>
</html>

java_recruit_info/job51/templates/job51/segment_count_ajax.html
{% extends "job51/layout.html" %}
{% load staticfiles %}
{% block title %} 职位列表页 {% endblock %}
{% block MainContent %}
    <div class="breadcrumb">
        <li>统计</li>
        <li>关键词</li>
    </div>
    <div class="page-header ">
        <span class="h3">关键词列表统计</span>
        <span class="h4 pull-right">
            <a href="{% url 'job:segment_count_sum'%}?jump_to=1">图表展示</a>
        </span>
    </div>
     <div id="table"></div>
    <input type="hidden" id="ajx_url" value="{% url 'job:segment_count_sum_ajax'%}">
    <script>
        $(function () {
            var ajx_url = $("#ajx_url").val();
            $("#table").bootstrapTable({
                url:ajx_url,
                method:'get',
                dataType:'json',
                contentType: "application/x-www-form-urlencoded",
                striped: true, //是否显示行间隔色
                sortable:true,
                sidePagination: "client",           //分页方式：client客户端分页，server服务端分页（*）
                showColumns:true,
                search: true,//是否显示表格搜索，此搜索是客户端搜索，不会进服务端
                pagination:true,
                queryParams:function () {
                    return {};
                },
                minimumCountColumns:2,
                pageNumber:1,                       //初始化加载第一页，默认第一页
                pageSize: 20,                       //每页的记录行数（*）
                pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
                uniqueId: "job_id",                     //每一行的唯一标识，一般为主键列
                showExport: true,
                exportDataType: 'all',
                columns:[
                    {
                        field: '',
                        title: '序号',
                        align : 'center',
                        formatter: function (value, row, index) {
                             return index+1;
                         }
                    },
                    {
                        field : 'key_word',
                        title : '关键词',
                        width: '50%',
                        align : 'center',
                        valign : 'middle',
                        sortable : true
                    }, {
                        field : 'count',
                        title : '总数',
                        width:  '50%',
                        align : 'center',
                        valign : 'middle',
                        sortable : true
                    }]
            })
        });
    </script>
 {% endblock %}

java_recruit_info/job51/templates/job51/segment_count_chart.html
{% extends "job51/layout.html" %}
{% load staticfiles %}
{% block title %} 职位列表页 {% endblock %}
{% block MainContent %}
    <div class="breadcrumb">
        <li>统计</li>
        <li>关键词</li>
    </div>
   <div class="page-header ">
        <span class="h3">关键词图表统计</span>
        <span class="h4 pull-right">
            <a href="{% url 'job:segment_count_sum'%}">列表展示</a>
        </span>
    </div>
    <div id="main" style="height: 600px"></div>
    <script src="{% static 'js/echarts-all.js' %}"></script>
    <script>
        var myChart = echarts.init(document.getElementById('main'));

        $(function () {
             $.get('/job/job/segment_count_sum/chart/', function (data) {
                var resp = JSON.parse(data);
                 option = {
                    tooltip : {
                        trigger: 'axis',
                        axisPointer: {
                            type: 'shadow',
                            label: {
                                show: true
                            }
                        }
                    },

                    calculable : true,
                    legend: {
                        data:['关键词', '总数'],
                        itemGap: 5
                    },
                    grid: {
                        top: '12%',
                        left: '1%',
                        right: '10%',
                        containLabel: true
                    },
                    xAxis: [
                        {
                            type : 'category',
                            data : resp.keys
                        }
                    ],
                    yAxis: [
                        {
                            type : 'value',
                            name : 'KeyWord'
                        }
                    ],
                    dataZoom: [
                        {
                            show: true,
                            start: 94,
                            end: 100
                        },
                        {
                            type: 'inside',
                            start: 94,
                            end: 100
                        },
                        {
                            show: true,
                            yAxisIndex: 0,
                            filterMode: 'empty',
                            width: 30,
                            height: '80%',
                            showDataShadow: false,
                            left: '93%'
                        }
                    ],
                    series : [
                        {
                            name: '总数',
                            type: 'bar',
                            data: resp.values
                        }
                    ]
                };
                 myChart.setOption(option);
             });
        })
    </script>
 {% endblock %}